#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Executa o larastan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Corrija os erros do larastan antes de commitar."
    exit 1
fi

# Executa os testes
./vendor/bin/pint
if [ $? -ne 0 ]; then
    echo "Corrija os erros dos testes antes de commitar."
    exit 1
fi

# Formata cada arquivo alterado no commit com o pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E ".php\{0,1\}$") || true
for FILE in $STAGED_FILES
do
    ./vendor/bin/pint $FILE > /dev/null >&1
    git add $FILE
done
