name: Laravel

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3

      - name: Instala as dependências
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Instala os assets
        run: npm install

      - name: Cria o banco de dados
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Executa os testes via pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/pest --parallel

      - name: Executa a análise de código via larastan
        run: vendor/bin/phpstan analyse
